### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SirBailey** [danielntech/miniaturepets#15]
Let the plugin read .zip files as well as .mpet files. The point of this is because you can lock a .zip file with a password so no one can steal paid pets. I have no clue if the password will affect it or not but it's something I would like to see be looked at.

Of cause I wouldn't make my free mpets a .zip so people can still learn off of them, it's just a safety reason for my(and others) paid pets.

I understand this won't stop users from leaking it but it will stop users who buy the pets and try to claim them as they're own to sell or other.

After writing this out I do believe the password would make it so the plugin can't read the files that are inside, would still like if you had a go if you can.

Thanks
Bailey

**Comment by danielntech** [comment]
Hi, when ZIP files are encrypted the internal contents of them is encrypted as well, meaning that the plugin will just throw an error that it is unable to read the ZIP's content. If you wish, a better suggestion would be using some sort of "serial keys" mechanism for MPets but I don't think we will do that. The best thing I can offer you is to make a plugin using the API that reads your encrypted MPet files so that people wouldn't be able to steal the code, nor use the pets without the decryption plugin.

Hope I was clear.

**Comment by SirBailey** [comment]
I thought so the same right after writing this whole thing out, it wouldn't good if I made my buyers download a plugin just to use a pet (plus I can't code haha). Oh well.

**Comment by danielntech** [comment]
Well coding is a big issue, but I thought of more as a "pet operator" and if you would of been able to code, you could of made some awesome things with it, among others such as decrypting zips. (Such as using the MPets API for more things)
