### ISSUE TITLE
Chicken pet Issue

### ISSUE THREAD

**Issue by Foxstone1** [danielntech/miniaturepets#49]
*Short description:*
 
MPet is loaded into the server, however it seems to be confliciting with something causing pets to load in as a chicken and a floating 'steve' head.

*Long description:* 

This issue arose out of the addition of the jar to teh server. We did properly stop the server, add the files, and then restarted the server. The heads in the GUI do not load the proper skins, and when summoned, all pets appear as a chicken underneath a floating head on an invisible armour stand. We tried loading the plugin to a local host and tested each plugin in the server has individually with no conflicts or issues whatsoever. That being said, we worked with "Daniel" in the support discord however all options seem to have been exhausted and directed us here. 
 
*Actions to repeat / ways of reaching the bug:* 

Bug was encountered on loading of the .jar file. 

*Miniature Pets Dump Link:*

https://pastebin.com/7KPi9Dq0

![2018-09-28_03 49 16](https://user-images.githubusercontent.com/43667891/46195821-57b27000-c2d3-11e8-8e3f-1b68909b0214.png)
![2018-09-28_03 45 42](https://user-images.githubusercontent.com/43667891/46195826-5a14ca00-c2d3-11e8-8f9f-3edb9c1a3862.png)
[error.txt](https://github.com/danielntech/miniaturepets/files/2427318/error.txt)

**Comment by BillyGalbreath** [comment]
He's using [Paper build 1444](https://i.imgur.com/LtJ5JDd.png) (MC 1.12.2) even though it's been renamed to `spigot.jar`. Theres been quite a few skull related fixes since then ([here](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0101-Don-t-tick-Skulls-unused-code.patch) 2 months ago, [here](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0230-Add-setPlayerProfile-API-for-Skulls.patch) 21 days ago, and [here](https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0325-Fix-client-rendering-skulls-from-same-user.patch) just yesterday, etc etc).

@Foxstone1 try upgrading your server jar to the [latest 1.12.2 build](https://papermc.io/downloads) and all your plugins (in case its a bug in a plugin). Always make sure you are using the latest softwares when reporting bugs. ;)
