### ISSUE TITLE
Not all pets showing in GUI

### ISSUE THREAD

**Issue by Felixx61** [danielntech/miniaturepets#55]
*Short description:* Not all pets shown in GUI since GUI-rework update

*Long description:* Triple checked all permissions are correct players still can't see some pets they have permission for - this has happened to multiple players and being reported daily.

*Actions to repeat / ways of reaching the bug:* Unknown, using latest version updated on spigot

*Miniature Pets Dump Link:*

**Comment by danielntech** [comment]
Please add your `/mpet dump` link.

**Comment by Kalasky** [comment]
The permission nodes work, but some mobs don't give you access to pages. So, for example, let's say I give a player just one mob and it was the sloth. The player wouldn't be able to access it because they can't even reach the page that it's on (spawner menu) in the first place. But for some reason when I give that same player a few other mobs on that page or on every page leading up to it (Not to sure how it works completely) then the player will be able to access the page that the sloth is on.
I hope that made sense.
